- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: yes
      tags:
      - nodejs
      # run nodejs tags
      - zsh
      # run zsh tags
  tasks:
    - include: fem-tasks/zsh.yml
    - include: fem-tasks/node.yml
