- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: yes
  tasks:
    - name: Install zsh
      apt: name=zsh
      tags:
        - zsh
    - name: Change default shell to zsh
      shell: chsh -s `which zsh
      tags:
        - zsh`
    - name: Install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)
      tags:
        - zsh"
    - name: Install zsh-autosuggestions
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
        dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
        tags:
          - zsh
    - name: Update our zshrc
      shell: sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions)/' ~/.zshrc
      tags:
        - zsh
    - name: Update cache
      apt:
        name: ['nodejs', 'npm']
        tags:
          - nodejs 
    - name: Install n
      npm: name=n
      tags:
          - nodejs 
    - name: Install nodejs 20.0.0 with n
      shell: n 20
      tags:
          - nodejs
