- hosts: localhost
  vars:
    key_work: "missoun_git"
    source_key: "./.ssh/id_rsa"
    source_key_work: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    dest_key_work: "{{ lookup('env', 'HOME') }}/.ssh/missoun_git"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: Update cache
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/prod-tools.yml
    - import_tasks: tasks/core.yml
    - import_tasks: tasks/vs-code.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/chrome.yml
    - import_tasks: tasks/brave.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/slack-setup.yml
    - import_tasks: tasks/npm-packages.yml
    - import_tasks: tasks/dotfile.yml
    - import_tasks: tasks/nvim-setup.yml
