- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: yes
      tags:
        #- node
      # run nodejs tags
      - zsh
      # run zsh tags
  tasks:
    #
    - include: tasks/zsh.yml
    #- include: tasks/node.yml
    #- include: tasks/node.yml
