- name: required libraries for docker
  become: true
  apt:
    name: ["curl", "ca-certificates", "curl", "gnupg", "lsb-release"]
  tags:
    - docker
    - install

- name: Docker Download
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    dest: /usr/share/keyrings/docker.gpg
  tags:
    - install
    - docker

- name: Docker ppa setting
  become: true
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
  tags:
    - install
    - docker

- name: docker apt installation
  apt:
    update_cache: yes
    name: docker-desktop-amd64.deb
  tags:
    - install
    - docker
