- name: required libraries
  become: true
  apt:
    name: ["curl", "wget", "apt-transport-https"]
  tags:
    - github
    - install

- name: Create necessary folder if necessary
  become: true
  shell: mkdir -p -m 755 /etc/apt/keyrings
  tags:
    - github
    - install

- name: Download github tool
  get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
  tags:
    - github
    - install

- name: GH ppa settings
  become: true
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list
  tags:
    - github
    - install

- name: GH installation
  become: true
  apt:
    update_cache: yes
    name: gh
  tags:
    - github
    - install

