- name: Vscode
  get_url:
    url: https://vscode.download.prss.microsoft.com/dbazure/download/stable/89de5a8d4d6205e5b11647eb6a74844ca23d2573/code_1.90.0-1717531825_amd64.deb
    dest: /tmp/vscode.deb
  tags:
    - install
    - vscode

- name: Remove Any previous slacks
  become: true
  apt:
    name: slack-desktop
    state: absent
  tags:
    - install
    - vscode

- name: Vscode install .deb package
  become: true
  apt:
    name: /tmp/vscode.deb
  tags:
    - install
    - vscode
