- name: required libraries for vscode
  become: true
  apt:
    name: ["curl", "apt-transport-https", "gpg", "wget"]
  tags:
    - code
    - install
- name: code archive-keyring.gpg download
  shell: wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
  tags:
    - code
    - install

- name: install gpg
  shell: install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
  tags:
    - code
    - install

- name: code PPA setting
  become: true
  shell: echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | tee /etc/apt/sources.list.d/vscode.list > /dev/null
  tags:
    - code
    - install

- name: code apt installation
  become: true
  apt:
    update_cache: yes
    name: code
  tags:
    - code
    - install
