- name: Install zsh
  apt: name=zsh
  tags:
    - zsh
- name: Change default shell to zsh
  shell: chsh -s `which zsh`
  tags:
    - zsh
- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - zsh
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
    tags:
      - zsh
- name: Update our zshrc
  shell: sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions)/' ~/.zshrc
  tags:
    - zsh
